language: go
env:
  global:
    - PACKAGE_VERSION=0.1.$TRAVIS_BUILD_NUMBER$TRAVIS_TAG
go:
  - "1.10.3"
before_install:
  - sudo apt-get install cmake git build-essential s3cmd
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - vendor/gocv.io/x/gocv/travis_build_opencv.sh
  - mkdir build
  - go build -ldflags '-s -w -extldflags "-L./opencv/build/lib"' -o build/lipovision
  - cp opencv/build/lib/* build/
script: go test ./...
after_success:
  - echo $TRAVIS_COMMIT_RANGE > build/CHANGELOG
  - mkdir pkg
  - tar -acf build/* pkg/lipovision-$PACKAGE_VERSION.tar.gz
  - md5 -q pkg/lipovision-$PACKAGE_VERSION.tar.gz > pkg/lipovision-$PACKAGE_VERSION.md5
  - s3cmd put --recursive pkg/* --access_key=$SPACES_ACCESS_KEY --secret_key=$SPACES_SECRET_KEY --host=$SPACES_ENDPOINT --host-bucket=$SPACES_BUCKET.$SPACES_ENDPOINT s3://$SPACES_BUCKET/$TRAVIS_OS_NAME/