language: go
go:
  - "1.10.3"
before_install:
  - sudo apt-get install cmake git build-essential
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - git clone https://github.com/opencv/opencv.git opencv
  - cd opencv
  - git checkout 9e1b1e5
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=OFF -DENABLE_CXX11=ON -DWITH_IPP=OFF -DWITH_MSMF=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_DOCS=OFF -DENABLE_PRECOMPILED_HEADERS=OFF -DBUILD_opencv_saliency=OFF -DCPU_DISPATCH= -Wno-dev ..
  - make all
  - cd ../..
  - mkdir build
  - go build -ldflags '-extldflags "-L./opencv/build/libs"' -o build/lipovision
  - cp opencv/build/lib/* build/
script: go test ./...