language: go
cache: vendor # Nice to not install and compile OpenCV from zero evry time
env:
  global:
    - PACKAGE_VERSION=0.1.$TRAVIS_BUILD_NUMBER$TRAVIS_TAG # Special builds will have a tag
    - OPENCV_VERSION=3.4.2
go:
  - "1.10.3"
addons:
  apt:
    packages:
    - libgmp-dev
    - build-essential
    - cmake
    - git
    - libgtk2.0-dev
    - pkg-config
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - libtbb2
    - libtbb-dev
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libjasper-dev
    - libdc1394-22-dev
    - xvfb
    - s3cmd
before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - GRAPHICAL=ON vendor/gocv.io/x/gocv/travis_build_opencv.sh
  - mkdir build
  - export PKG_CONFIG_PATH=$PWD/opencv-$OPENCV_VERSION/unix-install/
  - go build -ldflags '-s -w' -o build/lipovision
  - cp opencv/build/lib/* build/
script: go test ./...
after_success: # Compile a list of changes, tarball everything, make md5 and upload to artifact repo 
  - echo $TRAVIS_COMMIT_RANGE > build/CHANGELOG
  - mkdir pkg
  - tar -acf build/* pkg/lipovision-$PACKAGE_VERSION.tar.gz
  - md5 -q pkg/lipovision-$PACKAGE_VERSION.tar.gz > pkg/lipovision-$PACKAGE_VERSION.md5
  - s3cmd put --recursive pkg/* --access_key=$SPACES_ACCESS_KEY --secret_key=$SPACES_SECRET_KEY --host=$SPACES_ENDPOINT --host-bucket=$SPACES_BUCKET.$SPACES_ENDPOINT s3://$SPACES_BUCKET/$TRAVIS_OS_NAME/
