language: go
cache: vendor # Nice to not install and compile OpenCV from zero evry time
env:
  global:
    - PACKAGE_VERSION=0.1.$TRAVIS_BUILD_NUMBER$TRAVIS_TAG # Special builds will have a tag
go:
  - "1.10.3"
before_install:
  - sudo apt-get install cmake git build-essential s3cmd
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - sudo GRAPHICAL=ON vendor/gocv.io/x/gocv/travis_build_opencv.sh
  - mkdir build
  - ls -lah
  - ls -lah open*/
  - ls -lah vendor/gocv.io/x/gocv/
  - pkg-config --cflags opencv
  - go build -ldflags '-s -w' -o build/lipovision
  - cp opencv/build/lib/* build/
script: go test ./...
after_success: # Compile a list of changes, tarball everything, make md5 and upload to artifact repo 
  - echo $TRAVIS_COMMIT_RANGE > build/CHANGELOG
  - mkdir pkg
  - tar -acf build/* pkg/lipovision-$PACKAGE_VERSION.tar.gz
  - md5 -q pkg/lipovision-$PACKAGE_VERSION.tar.gz > pkg/lipovision-$PACKAGE_VERSION.md5
  - s3cmd put --recursive pkg/* --access_key=$SPACES_ACCESS_KEY --secret_key=$SPACES_SECRET_KEY --host=$SPACES_ENDPOINT --host-bucket=$SPACES_BUCKET.$SPACES_ENDPOINT s3://$SPACES_BUCKET/$TRAVIS_OS_NAME/